- zephyr/adapter/src/wifi/esp_wifi_adapter.c
function should not return int value
> wifi: fix wrong void return value

- components/esp_timer/src/esp_timer_impl_lac.c
> timer: fix LAC timer log error

- components/esp_timer/src/esp_timer.c
fix unknown symbol error during /tests build
> esp_timer: fix undefined reference

- zephyr/CMakeLists.txt
Zephyr community uses COUNTER instead of TIMER.
This commit replaces the config macro name to avoid confusion.
Signed-off-by: Glauber Maroto Ferreira <glauber.ferreira@espressif.com>
> esp32: counter: replaces CMakeLists.txt config macro name

- components/esp_event/include/esp_event.h
- zephyr/adapter/src/wifi/esp_event.c
Let wifi interface to be up when wifi lib
announces START event.
Updated legacy wifi events.
> wifi: fix net_if_up event start

- components/spi_flash/flash_ops.c
- zephyr/adapter/include/common/cache_utils.h
Includes:
- SPI Flash guard functions
- Common cache state control API
Signed-off-by: Glauber Maroto Ferreira <glauber.ferreira@espressif.com>
> hal: esp32: spi_flash: adds support for SPI Flash operations

- zephyr/CMakeLists.txt
This shall be included once newlib support gets in place
and PSRAM workaround is verified.
> linker: remove newlib linker

- zephyr/CMakeLists.txt
- zephyr/adapter/src/heap_caps.c
Fixes SPIRAM allocation being placed in internal memory
Signed-off-by: Shubham Kulkarni <shubham.kulkarni@espressif.com>
> hal: Add wrapper for k_malloc

- zephyr/CMakeLists.txt
> cmake: fix directory include

- components/esp_timer/src/esp_timer_impl_lac.c
- zephyr/esp32/CMakeLists.txt
esp_time_impl.c file uses newlib calls
that are not available in Zephyr.
It also removes the same source from build as
it it not used at all.
> hal: remove unused newlib file dependency

- tools/cmake/project.cmake
skip idf selection of the toolchain and let
compiler be defined by zephyr cmake
> toolchain: use zephyr defined toolchain

- tools/cmake/project.cmake
This reverts commit 55099bd86fe28ac457d4b0705331be72752c2786.
> Revert "toolchain: use zephyr defined toolchain"

- zephyr/esp32/src/heap_caps.c
Z_STRUCT_SECTION_ITERABLE was deprecated in order
to allow the same macro to be used along application.
> macro: update macro usage

- components/log/log_noos.c
change include order of zephyr header file
depending on the selected target.
> hal: log: fix macro redefinition on esp32

- zephyr/esp32s2/CMakeLists.txt
by adding related hal paths and sources.
> hal: esp32s2: counter driver support

- zephyr/esp32c3/src/bt/esp_bt_adapter.c
This PR changes the bluetooth adapter to replace the hardcoded interrupt management functions with the new interrupt allocator APIs from esp32c3 interrupc controller driver from Zephyr kernel.
> hal: bt: uses the interrupt allocator in bluetooth

- zephyr/esp32c3/CMakeLists.txt
To enable usage of esp32c3 in the gpio driver
> hal: esp32c3: add gpio infra support

- west/tools.py
This forces python calls to use the version
exported by west tool.
> python: use west python tool

- components/esp32/clk.c
- components/esp32s2/clk.c
- components/esp32s3/clk.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
This enabled proper soc clock settings defintions.
> clock: add soc specific clock functions

- tools/idf_monitor.py
- west/tools.py
-addr2line was set for esp32 by default. Now it
searches for proper SOC device.
> monitor: add proper toolchain name and path

- components/esp_timer/src/esp_timer.c
- components/esp_timer/src/esp_timer_impl_systimer.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c3/include/crypto/esp_config.h
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/common/esp_read_mac.c
- zephyr/esp32c3/src/heap_adapter.c
- zephyr/esp32c3/src/stubs.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/wpa_supplicant/port/os_riscv.c
By adding wifi adapter and wpa_supplicant files.
> hal: wifi: add support of wifi subsystem for esp32c3

- components/esp_timer/private_include/esp_timer_impl.h
- components/esp_timer/src/esp_timer_impl_systimer.c
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
This PR fixes the potential break of the wifi and bt subsystems in esp32c3 after interrupt allocator driver got merged in Zephyr main branch by removing the manual interrupt handling and placing the interrupt setting using the zephyr interrupt allocator driver.
> hal: esp32c3: handle wifi and bt using interrupt allocator driver

- components/esp32/clk.c
- components/esp32s2/clk.c
- components/esp32s3/clk.c
MCUboot build issues were observed as Zephyr specific files are included in build
> clock: Fix build issues when building non Zephyr apps

- components/wpa_supplicant/src/crypto/crypto_mbedtls-ec.c
mbedTLS v3.0.0 released in 2021-07-07 has lots of updates
which breaks current wpa supplicant implementation.
Current, only enabling private definitions and adding extra
RNG implementation is necessary.
> crypto: update wpa supplicant to support mbedtls v3.0.0

- components/esp_hw_support/port/esp32/rtc_clk.c
- components/esp_hw_support/port/esp32/rtc_clk_common.h
- components/esp_hw_support/port/esp32/rtc_clk_init.c
- components/esp_hw_support/port/esp32c3/rtc_clk_init.c
- components/esp_hw_support/port/esp32c3/rtc_time.c
- components/esp_hw_support/port/esp32s2/rtc_clk_common.h
- components/esp_hw_support/port/esp32s2/rtc_clk_init.c
- components/esp_hw_support/port/esp32s2/rtc_time.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Also add cmakes flags to overcome warnings
> hal: clock: add rtc files to unify clock control

- zephyr/esp32c3/CMakeLists.txt
to enable timer driver for esp32c3
> hal: esp32c3: add timer group hal

- zephyr/esp32/CMakeLists.txt
removes references to inexistent include directories.
> hal: soc: esp32: cmake clean-up

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Add proper wdt_hal source files to enable
driver unification.
> wdt: added hal sources

- components/esp_wifi/src/phy_init.c
by locking the irq just once when the nesting is zero.
This fix is required to enable the WIFI to get working in SMP builds.
> esp_wifi: phy_init: fix the phy critical section

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
This enables handling pins properly as some
gpios are configured over RTC registers.
> gpio: add rtc_io interface

- zephyr/esp32c3/src/linker/esp32c3.rom.alias.ld
to make them visible in zephyr side.
> esp32c3: add usb uart rom functions

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
This clears UART driver from keeping routing
signals hardcode in uart driver
> uart: add signal sources map

- zephyr/esp32s2/src/linker/esp32s2.rom.alias.ld
Add alias to force the esp_rom prefix.
> soc: esp32s2: add new alias used in mcuboot feature

- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
Nested lock and unlock events handler was missing.
> bt: adapter: fix missing nested lock check

- zephyr/scripts/README.md
fixes documentation typo
Signed-off-by: Glauber Maroto Ferreira <glauber.ferreira@espressif.com>
> typo: pinctrl: scripts: README

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
which is no longer required since refactorings done
on the UART driver to bring pinctrl support.
> hal: uart: remove file dependency

- zephyr/esp_shared/include/host_flash/cache_utils.h
Remove build warning due to implicity declaration.
> flash: add missing cache include

- components/bootloader_support/src/bootloader_common.c
- components/driver/periph_ctrl.c
- components/esp32/clk.c
- components/esp32/spiram.c
- components/esp32/spiram_psram.c
- components/esp32s2/clk.c
- components/esp32s2/spiram.c
- components/esp32s2/spiram_psram.c
- components/esp_timer/src/esp_timer.c
- components/esp_timer/src/esp_timer_impl_lac.c
- components/esp_timer/src/esp_timer_impl_systimer.c
- components/esp_wifi/src/phy_init.c
- components/log/log_noos.c
- components/spi_flash/flash_mmap.c
- components/wpa_supplicant/port/include/os.h
- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32/src/heap_caps.c
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32/src/wpa_supplicant/port/os_xtensa.c
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/common/esp_read_mac.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/wpa_supplicant/port/os_riscv.c
- zephyr/esp32s2/src/heap_caps.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wpa_supplicant/port/os_xtensa.c
- zephyr/esp_shared/include/host_flash/cache_utils.h
- zephyr/esp_shared/src/common/esp_system_api.c
- zephyr/esp_shared/src/host_flash/cache_utils.c
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.
> zephyr: update include paths to use <zephyr/...>

- zephyr/esp32/src/bt/esp_bt_adapter.c
This fixes build warnings related to pointer address
> bt: remove pointer address when loading rom data

- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
This also fixes wrong spinlock creation
> wifi: organize wifi adapter to use common malloc calls

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Update naming configuration for ESP32 timer/counter
> cmake: fix timer config naming

- components/wpa_supplicant/port/include/os.h
- zephyr/esp_shared/include/host_flash/cache_utils.h
<zephyr/zephyr.h> is just a shim to <zephyr/kernel.h>.
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
> hal: use s/<zephyr/zephyr.h>/<zephyr/kernel.h>

- components/esp_hw_support/port/esp32/spiram_psram.c
- components/esp_hw_support/port/esp32s2/spiram_psram.c
- components/spi_flash/esp32/flash_ops_esp32.c
- components/spi_flash/esp32c3/flash_ops_esp32c3.c
- components/spi_flash/esp32s2/flash_ops_esp32s2.c
- components/spi_flash/flash_ops.c
- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
This also removes the IRAM_ATTR attribute from ff declaration from hal_v4.4.1 branch.
> drop IRAM_ATTR attribute from forward declaration

- components/esp_wifi/include/esp_wifi_types.h
After Zephyr's wifi updates, a few declarations became
redefined, causing build to fail. This adds ESP32 prefix
into those private enums to fix it.
> wifi: rename private enums to avoid redefinition and errors

- components/driver/periph_ctrl.c
After SDK 0.15.0 update, array out of bounds warning
came up. This fix the warning with no harm to hal.
> bugfix: array out of bounds build warning

- components/esp_hw_support/regi2c_ctrl.c
- components/hal/esp32/include/hal/interrupt_controller_ll.h
- components/hal/esp32s2/include/hal/interrupt_controller_ll.h
Replace <zephyr/zephyr.h> with <zephyr/kernel.h>, as it will be
deprecated soon.
> hal: s/zephyr.h/kernel.h

- .gitignore
When hal_espressif is integrated as git submodule, the blobs cause a dirty status, which cannot be fixed in the top repository.
> blobs: Add blobs to .gitignore

- components/hal/esp32c3/include/hal/gdma_ll.h
- zephyr/esp32c3/CMakeLists.txt
Add gdma driver source files to zephyr build.
Signed-off-by: Lucas Tamborrino <lucas.tamborrino@espressif.com>
> driver: gdma: add source files to build

- components/driver/include/driver/uart.h
- components/esp_hw_support/port/esp32/rtc_sleep.c
- components/esp_hw_support/port/esp32c3/rtc_sleep.c
- components/esp_hw_support/port/esp32s2/rtc_sleep.c
- components/esp_hw_support/sleep_modes.c
- components/esp_hw_support/sleep_retention.c
- components/esp_system/port/brownout.c
- components/esp_system/port/soc/esp32/clk.c
- components/esp_system/port/soc/esp32c3/clk.c
- components/esp_system/port/soc/esp32s2/clk.c
- components/hal/esp32s2/brownout_hal.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c3/include/stubs.h
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s2/include/stubs.h
- zephyr/esp_shared/components/driver/gpio.c
- zephyr/esp_shared/include/stubs.h
HAL changes to bring Power Management support for Espressif SoCs on Zephyr RTOS.
> hal: esp32xx: power management: HAL support

- zephyr/esp32/CMakeLists.txt
Removes source used for clock init when ESP32_NET is defined.
> hal: pm: esp32_net: exclusion of clk source

- components/esp_common/include/esp_check.h
Make sure hal MACROS as such as ESP_RETURN_ON_ERROR uses Zephyr Logging subsystem instead of esp-idf interface.
This shall be the output when errors in `hal_espressif` sources: (here tested in hello_world sample):  
```c
*** Booting Zephyr OS build v3.2.0-rc3-93-ge477d706943a  ***
Hello World! esp32
[00:00:00.425,000] <err> esp32: main(13): error
```
> macro: convert ESP macro to use Zephyr's logging

- components/esp_phy/src/phy_init.c
ESP32-C3 usb-serial interface does not work when Wi-Fi is enabled. This fixes that by allowing hal_espressif to proper handle this pin when PHY is enabled.
> driver: uart: allow esp32c3 usb-serial to work with wifi

- components/esp_common/include/esp_check.h
This reverts commit cc411a9dcbb7c90cfe8ff9c2a93f0d966069890d, which adds Zephyr logging subsystem into esp-check internals. However, it won't work with multiple includes due to Zephyr Macro.
> Revert "macro: convert ESP macro to use Zephyr's logging"

- components/esp_system/port/soc/esp32/clk.c
- components/esp_system/port/soc/esp32c3/clk.c
- components/esp_system/port/soc/esp32s2/clk.c
Clock control needs to wait TX idle. However, it only needs to do that if console/uart is enabled.
> pm: clock: check console status for proper flushing

- zephyr/esp_shared/components/esp_pm/pm_impl.c
UART baudrate is already checked during drivers initialization.
> pm: remove uart baudrate check from its source

- components/driver/esp32c3/rtc_tempsensor.c
- components/driver/esp32s2/rtc_tempsensor.c
- components/efuse/esp32c3/esp_efuse_rtc_calib.c
- components/esp_common/include/esp_compiler.h
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Add basic support for measuring die temperature on ESP32 targets S2 and C3.
> driver: esp32: sensor: Add die temperature support

- tools/idf_monitor_base/console_parser.py
- tools/idf_monitor_base/serial_handler.py
- west/tools.py
Adds end-of-line argument parser in order to have
the console proper working without scrambling texts.
Fixes #162 
> monitor: fix missing eol in console parser

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
After Zephyr's SDK 0.15.2, base64 source is causing build redefinition.
> base64: remove from wpa source to avoid redefition

- zephyr/esp_shared/include/stubs.h
Retrieve CPU clock from DTS instead of custom CONFIG value. For ESP32 and ESP32-S2 where the CPU clock is linked to CCOUNT, it works as is. For ESP32-C3 where systimer is used, it does not work.
> stubs: fix default CPU clock definition

- west/tools.py
Run the monitor using actual working directory, which is more likely to have build directory.  As we should be able to build anywhere in the west workspace.
Details in https://github.com/zephyrproject-rtos/zephyr/discussions/33521
> west: espressif monitor path

- components/esp_hw_support/port/esp32/rtc_time.c
- components/esp_hw_support/port/esp32s2/rtc_time.c
- components/esp_hw_support/port/esp32s3/rtc_time.c
Clock calibration can get stuck due to usage of
esp_rom_delay_us greater than OS tick rate.
This PR updates this usage to kernel OS delay instead.
ESP32C3 needs to stick with default esp_rom_delay_us as it uses custom systimer, which is not ready yet during clock calibration.
> clock: use RTOS timer instead of esp_rom

- components/esp_hw_support/port/esp32s3/rtc_clk_common.h
- zephyr/esp_shared/include/stubs.h
This fixes build warning due to MHZ definition and missing S3 CPU name convention.
> clock: esp32s3: fix build warnings and CPU name

- components/esp_hw_support/port/esp32/spiram_psram.c
- zephyr/esp32/CMakeLists.txt
Update SPIRAM/flash WP SD3 pin configuration to be called
from bootloader source file. This will automatically check
whether WP_SD3 pin was customized or from efuse values.
Fixes [#54005](https://github.com/zephyrproject-rtos/zephyr/issues/54005)
> bugfix: fix SPIRAM WP pin configuration

- tools/idf_monitor_base/output_helpers.py
- west/tools.py
This PR provides the correct elf and build paths for the `west espressif monitor` if sysbuild has been used to create build directory structure.
> Add sysbuild support for west tools

- components/hal/esp32s3/include/hal/uart_ll.h
RS485 support in ESP32-S3 uses different naming for some drivers struct entries. This fix it.
> driver: uart_ll: fix wrong rs485 bit reference

- components/esptool_py/project_include.cmake
This fix brings from esp-idf a patch that
allows the bootloader binary not to append SHA256 digest when flash size is set to 'detect'.
> esptool: add option to remove SHA256 digest

- components/esp_hw_support/port/esp32/spiram.c
- components/esp_hw_support/port/esp32s2/spiram.c
This removes FreeRTOS entries that are not used and is currently blocking SPIRAM build.
> spiram: remove unused includes

- zephyr/esp_shared/include/stubs.h
Only zephyr/devicetree.h is needed.
> zephyr: include the right header

- zephyr/CMakeLists.txt
Make sure this CMakeLists.txt content is only used
for ESP32 builds. Otherwise all other xtensa boards will use it.
> cmake: add guard condition to HAL_ESPRESSIF usage

- zephyr/CMakeLists.txt
As an addition to #207, update CMakeLists in order to check RF libraries only when Wi-Fi or BT are enabled.
> cmake: check RF libraries only when required

- components/hal/esp32c3/include/hal/soc_ll.h
Resetting via Zephyr sys_reboot() on ESP32C3 I was seeing intermittent hangs on restart. Changing the reset mode in the HAL from a processor level to system level reset solved this.
> hal: esp32c3: soc_ll Software reset system

- components/esp_phy/src/phy_init.c
ESP32-S2 is not able to build due to call to BB reset. This excludes this SOC from that condition.
> phy: esp32s2: fix build issue

- components/esp_wifi/include/esp_private/wifi_os_adapter.h
Wi-Fi sample code is failing due to wrong configuration.
> wifi: esp32s2: fix wrong struct definition

- components/esp_wifi/include/esp_wifi_types.h
- components/wifi_provisioning/src/manager.c
- components/wpa_supplicant/esp_supplicant/src/esp_scan.c
Update the typedef name after Zephyr added the manager feature with the wifi scan type option colliding with the naming used in hal_espressif.
> components: Fix WIFI_SCAN_TYPE after Zephyr update

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Some functionality guarded with CONFIG_PM is now needed by CONFIG_POWEROFF. While it is wrong to add such dependencies in a HAL, it allows us to move on for now. A fixme note has been added.
> zephyr: esp32/c3/s2: compile power related files for poweroff

- zephyr/esp_shared/src/common/heap_caps.c
The existing heap starts at the beginning of SPIRAM which is also occupied by the WiFi stack if CONFIG_ESP32_WIFI_NET_ALLOC_SPIRAM is enabled.  This results in memory corruption.
Update the heap code to use a linker-description symbol _spiram_heap_start for setting the starting point of the SPIRAM heap.
Requires matching change to the .ld files in the Zephyr soc code:  https://github.com/zephyrproject-rtos/zephyr/pull/61365
Fixes: 61359
> heap: add SPIRAM heap offset and size

- zephyr/esp_shared/src/common/heap_caps.c
Prefix configuration item with ESP to avoid conflicts with other procesor architectures.
> heap: rename CONFIG_SPIRAM_HEAP_SIZE

- components/esp_timer/src/esp_timer_impl_lac.c
- zephyr/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
- zephyr/esp_shared/include/stubs.h
Allows building ESP32-S3 AMP SoC.
> soc: esp32s3: add esp32s3_net series

- components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
- components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld
- components/esp_rom/esp32s2/ld/esp32s2.rom.newlib-funcs.ld
- components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
RF libraries expects ROM functions as a form of
compatibility. Using different implementations can cause Wi-Fi/BLE errors/crashes. This PR adds a few libc functions to ESP32 environment.
> cmake: load all libc rom functions by default

- zephyr/esp32s3/CMakeLists.txt
Initially this was split between procpu and appcpu. Now it can be added as common source.
> cmake: esp32s3: make clk source code common

- components/esptool_py/esptool/esptool/bin_image.py
Parse ELF section alignment values and use those to check to see if successive sections are separated because of them. Pad a previous section if doing so would cause it to precisely align with the next section start address. This ensures that alignment requirements don't spoil our attempt to merge sections.
> esptool: Pad sections to account for alignment

- zephyr/esp_shared/components/esp_pm/pm_impl.c
MP_NUM_CPUS is being deprecated in favor of CONFIG_MP_MAX_NUM_CPUS in Zephyr.
> zephyr: Use CONFIG_MP_MAX_NUM_CPUS

- components/bootloader_support/include/esp_app_format.h
- components/bootloader_support/src/esp32s3/bootloader_esp32s3.c
- components/bootloader_support/src/esp32s3/bootloader_soc.c
- components/bootloader_support/src/esp32s3/flash_encryption_secure_features.c
- components/bootloader_support/src/esp32s3/secure_boot_secure_features.c
- components/efuse/esp32s3/esp_efuse_rtc_calib.c
- components/efuse/esp32s3/esp_efuse_table.c
- components/efuse/esp32s3/include/esp_efuse_table.h
- components/esp_common/include/esp_assert.h
- components/esp_hw_support/include/esp_private/sar_periph_ctrl.h
- components/esp_hw_support/port/esp32s3/rtc_init.c
- components/esp_hw_support/port/esp32s3/rtc_pm.c
- components/esp_hw_support/port/esp32s3/rtc_sleep.c
- components/soc/esp32s3/include/soc/rtc.h
- components/soc/esp32s3/include/soc/rtc_cntl_reg.h
Current ESP32-S3 bootloader only supports up to 16MB internal flash. Due to this reason, boards with flash size greater then 16MB will fallback to 2MB, making device tree regions incorrect and bugged.
> esp32s3: update bootloader to enable all flash memory ranges

- components/spi_flash/flash_mmap.c
> flash: update free() call to meet zephyr environment

- components/esp_system/port/soc/esp32/reset_reason.c
- components/esp_system/port/soc/esp32c3/reset_reason.c
- components/esp_system/port/soc/esp32s2/reset_reason.c
- components/esp_system/port/soc/esp32s3/reset_reason.c
Zephyr won't init constructor functions if CPP is disabled. By default, it is disabled.
This makes reset_reason_init public so Zephyr calls this during SoC startup.
> system: make reset reason init public

- components/esp_eth/src/esp_eth_mac_esp.c
- components/hal/emac_hal.c
- components/hal/include/hal/emac_hal.h
s/emac_hal_iomux_rmii_clk_ouput/emac_hal_iomux_rmii_clk_output
> emac_hal: fix typo

- components/esp_timer/src/esp_timer.c
The thread object s_timer_task is statically allocated. Therefore its memory should not be freed via k_free().
> components: Remove improper k_free() in esp_timer

- zephyr/esp_shared/src/common/heap_caps.c
With recent main tree changes the correct way to determine the presense of the system heap is the K_HEAP_MEM_POOL_SIZE macro.
> zephyr: Use K_HEAP_MEM_POOL_SIZE instead of CONFIG_HEAP_MEM_POOL_SIZE

- zephyr/esp32/CMakeLists.txt
When building ADc and POWEROFF events, multiple rtc_io_hal.c were included.
Fix #261
> cmake: rtc_io: fix wrong include source

- components/esp_timer/src/esp_timer_impl_lac.c
- zephyr/CMakeLists.txt
- zephyr/esp32/CMakeLists.txt
- zephyr/esp_shared/include/stubs.h
ESP32_NET is now SOC_ESP32_APPCPU and a subset of SOC_SERIES_ESP32.
> zephyr: refactor esp32_net

- components/esp_phy/src/phy_init.c
ESP32S3 and ESP32C3 requires USB to be enabled
during phy initialization. In case it is not, USB interface won't work and will be disabled. The impact is that USB ACM0 port won't appear by default for flashing neither debugging.
> phy: enable usb when phy is initiallized

- zephyr/esp_shared/include/host_flash/cache_utils.h
The file relied on soc.h being indirectly included from kernel.h.
> zephyr: cache_utils: add missing include

- zephyr/esp_shared/src/boot/esp_loader.c
MCUboot requires that assert function in order to work when MCUBOOT_HAVE_ASSERT_H is set.
Fix #239
Fix https://github.com/mcu-tools/mcuboot/issues/1879
> mcuboot: add missing assertion function

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Patched longjmp to be context-switch safe
longjmp modifies the windowbase and windowstart
registers, which isn't safe if a context switch
occurs during the modification. After a context
switch, windowstart and windowbase will be
different, leading to a wrongly set windowstart
bit due to longjmp writing it based on the
windowbase before the context switch. This
corrupts the registers at the next window
overflow reaching that wrongly set bit.i
> system: make longjmp save for context switch

- components/hal/emac_hal.c
- components/hal/include/hal/emac_hal.h
Fix "ouput" to "output" keyword.
> emac: fix typo in emac function name

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
After hal_v5.1 update, base64 sources were re-included in wpa_supplicant files. This conflicts with Zephyr's base64 sources, so we remove it.
> wpa_supplicant: remove base64 from sources

- components/esp_timer/src/esp_timer_impl_systimer.c
Fixes esp_timer IRQ not being allocated when several peripherals are enabled. Fixes #74368
> hal: esp_timer: Relax ISR priority to avoid IRQ non allocated

- components/driver/deprecated/adc_dma_legacy.c
- components/driver/deprecated/adc_legacy.c
- components/driver/deprecated/dac_common_legacy.c
- components/driver/deprecated/timer_legacy.c
- components/efuse/src/esp_efuse_utility.c
- components/esp_adc/adc_common.c
- components/esp_hw_support/port/esp32c3/adc2_init_cal.c
- components/esp_hw_support/port/esp32s2/adc2_init_cal.c
- components/esp_hw_support/port/linux/esp_random.c
- components/esp_system/port/soc/esp32c2/reset_reason.c
- components/esp_system/port/soc/esp32h2/reset_reason.c
After #74682, constrcutor attribution was enabled in Zephyr. Remove this from hal until we can test all cases before allowing it to work.
> hal: remove all constructor attribute

- zephyr/esp32c6/CMakeLists.txt
Low level files to support GDMA
> hal: gdma: Add support to ESP32C6

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
bootloader_random_disable() call needs to be available for both mcuboot and simple boot builds.
> cmakelists: let bootloader sources into mcuboot build

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Forces gcc to treat register bitfield structs declared volatile as such,
thus treating problem of faulty writes on 32 bit peripheral registers.
> hal: gcc: Compiler flag for strict volatile bitfields

- west/tools.py
Ensure that the venv's Python executable is used, and convert the WindowsPath to a string.
> monitor: support using idf_monitor from a virtualenv on Windows

- components/hal/esp32c6/include/hal/clk_gate_ll.h
- components/hal/esp32c6/include/hal/usb_serial_jtag_ll.h
- components/hal/include/hal/usb_serial_jtag_types.h
Added LL files for clock control of USB JTAG peripheral
> hal: esp32c6: Clock control for USB JTAG peripheral

- components/esp_system/include/esp_task.h
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
Use CONFIG_ESP_WIFI_MAX_THREAD_PRIO instead of
hardcoded value in the `task_get_max_priority_wrapper`. The real priority is then calculated as
prio = (CONFIG_ESP_WIFI_MAX_THREAD_PRIO - 2)
during the wifi runtime.
> zephyr: esp_wifi_adapter: Use priority config

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Fix typos in the sources lists of SOCs CMakeLists.txt.
> Fix typos in SoCs sources list

- components/esp_phy/src/phy_init.c
This fixes issue when CONFIG_ASSERT is enabled and WiFi is used for an ESP32 e.g., 
`west build -p -b esp32_devkitc_wroom/esp32/procpu ./zephyr_os/zephyr/samples/net/wifi`
and setting CONFIG_ASSERT to true will result in:
```
ASSERTION FAIL [arch_irq_unlocked(key) || _kernel.cpus[0].current->base.thread_state & (((1UL << (0))) | ((1UL << (3))))] @ WEST_TOPDIR/zephyr/kernel/include/kswap.h:99
Context switching while holding lock!
[00:00:01.706,000] <err> os:  ** FATAL EXCEPTION
[00:00:01.706,000] <err> os:  **  A0 0x800d5158  SP 0x3ffb4820  A2 0x4  A3 0x3ffb4830
[00:00:01.706,000] <err> os:  **  PC 0x40085c77 VADDR 0
0x40085c77: xtensa_arch_except_epc at /Users/oscargoldring/git/powerhub-top/zephyr_os/zephyr/arch/xtensa/core/xtensa_asm2_util.S:209
[00:00:01.707,000] <err> os:  ** SAR 0x4 …
```
> Add PHY locking mechanism

- zephyr/port/pincfgs/esp32c2.yml
Pinctrl configuration for SPI support on ESP32C2/ESP8684
> drivers: spi: esp32c2: Pinctrl configuration

- components/hal/esp32c2/include/hal/ledc_ll.h
- components/soc/esp32c2/include/soc/soc.h
- zephyr/port/pincfgs/esp32c2.yml
Add LEDC PWM driver support for ESP32C2 and ESP8684
> hal: esp32c2: Add LEDC PWM support

- components/bootloader_support/src/bootloader_init.c
The ESP32 comes in a wide variety of chip and package revisions. Recent V3 revision brings important and major silicon and ROM fixes. To avoid isues, which comes from using the older revisions, we are restricting usage of older revisions, such as V0 and V1.
> Restrict supported ESP32 chip revisions

- components/hal/esp32c6/include/hal/clk_gate_ll.h
- components/soc/esp32c6/include/soc/soc_caps.h
Updates hal files to support clock control for RNG module.
> hal: rng: esp32c6: Clock control for TRNG

- components/spi_flash/flash_mmap.c
paddr_blocks should be freed by k_free() because it's allocated by k_malloc().
This issue is found by zephyrproject-rtos/zephyr#64159.
> spi_flash: Replace free() with k_free()

- components/bootloader_support/src/bootloader_clock_init.c
SPI flash configuration during boot requires clock to be configured to PLL80 before it occurs. Due to APB clock differences in C6 and a different boot sequence compared to IDF, conditions don't allow for SPI flash config to take place accordingly. To ensure all SoC's have the same behavior in case of SW reset, the conditions restricting clock configuration in case of SW reset were removed.
> boot: esp32c6: Fix SW restart

- components/esp_timer/src/esp_timer.c
Semaphore init check is wrong as 0 is the expected return
when success.
> esp_timer: fix semaphore init check

- zephyr/esp32s3/src/bt/esp_bt_adapter.c
Fix unused variable warning in bt adapter.
> zephyr: esp32s3: bt: Remove unused variable

- components/bootloader_support/src/esp32/bootloader_esp32.c
- components/bootloader_support/src/esp32c2/bootloader_esp32c2.c
- components/bootloader_support/src/esp32c3/bootloader_esp32c3.c
- components/bootloader_support/src/esp32c6/bootloader_esp32c6.c
- components/bootloader_support/src/esp32s2/bootloader_esp32s2.c
- components/bootloader_support/src/esp32s3/bootloader_esp32s3.c
- components/driver/include/esp_private/spi_common_internal.h
- components/spi_flash/spi_flash_os_func_app.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Current implementation does not use spi-flash functions to disable/enable cache and interrupts during flash write operations. In order to enable those functions, spi-flash needs to be initialized during bootloader_init, supplying necessary chip information to it.
> spi_flash: update initialization process and manage cache properly

- components/bootloader_support/src/esp32c2/bootloader_esp32c2.c
- components/bootloader_support/src/esp32c3/bootloader_esp32c3.c
- components/bootloader_support/src/esp32c6/bootloader_esp32c6.c
- components/bootloader_support/src/esp32s2/bootloader_esp32s2.c
- components/bootloader_support/src/esp32s3/bootloader_esp32s3.c
- components/spi_flash/esp_flash_spi_init.c
Fix usage of CONFIG_ESP_SIMPLE_BOOT after excluding the CONFIG_MCUBOOT from its area of validity.
> components: Fix simple-boot condition

- zephyr/port/include/stubs.h
Make sure ESP_CONSOLE_UART_NUM meets the proper SoC US_SERIAL por number.
> usb_serial: fix uart port when USB_SERIAL is used

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s3/CMakeLists.txt
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
Utilize the memory left unused by static allocation, and re-claim it dynamically using the Zephyr `k_heap` API for the ESP WiFi adapter purposes.
> Dynamic heap for ESP Wi-Fi

- components/esp_hw_support/sleep_modes.c
- components/esp_hw_support/sleep_retention.c
- components/esp_pm/pm_impl.c
When CONFIG_PM=y, some variables are not used. Handle it accordingly.
> build: remove unused variables when PM is enabled

- components/hal/ledc_hal.c
Initialize slow_clk with default value to avoid warnings.
> ledc: initialize variable to avoid build warning

- components/esp_hw_support/include/esp_private/adc_share_hw_ctrl.h
- components/esp_hw_support/port/esp32c3/adc2_init_cal.c
- components/esp_hw_support/port/esp32s2/adc2_init_cal.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
Changes to allow adc2_init_code_calibration() to be called during adc and wifi initialization on esp32s2 and esp32c3
Related to [PR#292](https://github.com/zephyrproject-rtos/hal_espressif/pull/292)
> drivers: adc/wifi: esp32s2/esp32c3: adc2_init_code_calibration() call prep

- components/wpa_supplicant/port/include/os.h
Fixes include for suseconds_t after SDK bump to 0.16.9-rc2
> wpa_supplicant: Fix include for suseconds_t

- components/bootloader_support/bootloader_flash/src/flash_qio_mode.c
- components/bootloader_support/src/bootloader_common_loader.c
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Allows QIO and QOUT flash modes to work in:
- esp32s2
- esp32s3
- esp32c2
- esp32c3
- esp32c6
> Allows QIO and QOUT flash modes

- components/wpa_supplicant/port/include/os.h
- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s3/src/bt/esp_bt_adapter.c
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
Each Wi-Fi and BT adapter uses the same approach to whether
use or not heap runtime feature.
This PR modify such usage in order to unify its access.
> rf: unify runtime heap call for bt and wifi adapters

- components/driver/touch_sensor/touch_sensor_common.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
The support for touch_sensor was lost when hal was updated to the v5.1.
This PR restores the touch_sensor support for the following SoCs:
- ESP32
- ESP32-s2
- ESP32-s3
> touch_sensor support restoration

- zephyr/esp32s3/src/bt/esp_bt_adapter.c
Make sure CONFIG_ESP_BT_HEAP_RUNTIME is properly checked.
> bt: esp32s3: fix wrong kconfig entry

- components/soc/esp32c2/include/soc/soc.h
Fix clock macros for compatibility with new HAL update.
> soc: esp32c2: Fix clock macros

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Add include path to expose bootloader headers for AMP SoCs.
> zephyr: AMP targets include

- zephyr/port/boot/esp_image_loader.c
- zephyr/port/include/boot/mcuboot_config/mcuboot_assert.h
When MCUBoot is used with ASSERT, build fails
due to missing mcuboot_assert_handler() call.
Current implementation conflicts with the way esp_image_loader.c is used. esp_image_loader.c should not handle mcuboot assertion as it is used for other means.
> mcuboot: assert: solve assert conflit

- components/esp_psram/esp32s3/esp_psram_impl_quad.c
- components/esp_psram/esp_psram_impl.h
The size table for this SPIRAM (IS6xWVS2M8ALL) is wrong. This PR adds the manufacturer identification and, based on that, chooses the right table size. For IS6xWVS2M8ALL, the size table starts at 8 Mib (1MB).
> psram: add ISSI IS6xWVS2M8ALL psram size

- components/esp_phy/src/phy_init.c
Ensure that locking and unlocking mechanisms support nestable critical sections to prevent deadlocks during recursive access.
> phy: add nestable lock/unlock handling

- zephyr/esp32s2/CMakeLists.txt
soc_random sources should be included for all build types.
> zephyr: esp32s2: Fix hw_init source file

- zephyr/esp32c3/CMakeLists.txt
Allow using ECO7 linker file based on SoC
revision.
> esp32c3: add ECO7 linker file

- zephyr/CMakeLists.txt
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
- zephyr/port/phy/phy_stubs.c
- zephyr/port/wifi/wifi_stubs.c
Add Wi-Fi stubs to allow CI build that does not
required binary blobs. It is useful to test
Wi-Fi driver and adapter.
> wifi: build with no blobs

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
Unify Kconfig name so both Wi-Fi and BLE share the same configuration parameter.
> cmakelists: update Kconfig entry for no blobs build

- zephyr/esp32c6/CMakeLists.txt
CMakeFile changes to support i2c on esp32c6
> esp32c6: add i2c hal support

- zephyr/esp32/CMakeLists.txt
- zephyr/esp32/include/bt/esp_bt.h
- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c3/include/bt/esp_bt.h
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32s3/CMakeLists.txt
- zephyr/esp32s3/include/bt/esp_bt.h
- zephyr/esp32s3/src/bt/esp_bt_adapter.c
- zephyr/port/bluetooth/bt_stubs.c
Add all bluetooth stubs in order to allow building without blobs.
> drivers: bluetooth: add stubs to allow CI testing without blobs

- zephyr/port/pincfgs/esp32c6.yml
Add i2c config to pinctrl generation yml to avoid regression (i2c already integrated).
> pinctrl: esp32c6: Add i2c config to pinctrl generation yml

- components/esp_common/include/esp_attr.h
Allow esp_attr.h file to retrieve SOC capabilities
from soc_caps.h. This also removes the " CONFIG_" prefix
from FAST and SLOW options as there is no Kconfig for that.
> attributes: add soc capabilities

- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
Make sure Wi-Fi adapter uses the interrupt allocator so that it won't mess with other peripheral's interrupt.
> wifi: isr: use interrupt allocator

- .github/CODEOWNERS
> github: add codeowners to improve review cycle

- zephyr/port/bluetooth/bt_stubs.c
Add missing BLE TX power control functions into
stubs list.
> ble: stubs: add missing stubs for BLE calls

- components/driver/deprecated/adc_legacy.c
It was observed that multiple calls to the adc#_config_channel_atten() functions caused execution crashes.
To avoid such crashes , this PR removes adc_hal_calibration_init() calls from adc#_config_channel_atten() functions, since adc_hal_calibration_init() is already called during Zephyr adc driver instantiation.
> adc: fix for crashes due to multiple calls to adc#_config_channel_atten()

- zephyr/port/pincfgs/esp32.yml
- zephyr/port/pincfgs/esp32s2.yml
i2s entries added to:
- zephyr/port/pincfgs/esp32.yml
- zephyr/port/pincfgs/esp32s2.yml
> esp32 & esp32s2: i2s support added

- zephyr/scripts/partitions/esp_genpartition.py
Add missing newline at the end of the generated files to pass the compliance checks.
> zephyr: scripts: fix partition generator

- components/esp_adc/adc_cali_curve_fitting.c
- components/esp_adc/esp32/adc_cali_line_fitting.c
- components/esp_adc/esp32c2/adc_cali_line_fitting.c
- components/esp_adc/esp32s2/adc_cali_line_fitting.c
Update hal_espressif to fix ADC source code with VLA, which is not C90 standard. To keep it up with Zephyr as is, update the necessary code and optimize the it.
> adc: update code to remove VLA from source

- zephyr/Kconfig.console
Adding ESP_CONSOLE to aggregate ESP_CONSOLE_UART and ESP_CONSOLE_USB_SERIAL_JTAG
> Kconfig.console: add ESP_CONSOLE to indicate UART or USB_SERIAL are enabled

- components/bootloader_support/bootloader_flash/include/bootloader_flash_priv.h
- zephyr/common/flash_init.c
- zephyr/common/include/flash_init.h
- zephyr/common/soc_init.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32/src/soc_init.c
- zephyr/esp32/src/soc_random.c
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c2/src/soc_init.c
- zephyr/esp32c2/src/soc_random.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32c6/src/soc_init.c
- zephyr/esp32c6/src/soc_random.c
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s2/src/soc_init.c
- zephyr/esp32s2/src/soc_random.c
- zephyr/esp32s3/CMakeLists.txt
- zephyr/esp32s3/src/soc_random.c
- zephyr/port/boot/esp_image_loader.c
- zephyr/port/bootloader/bootloader_flash.c
- zephyr/port/host_flash/cache_utils.c
This PR completely removes BOOTLOADER_BUILD dependency and make flash initialization
code unified across Simple Boot and MCUBoot.
> bootloader: update flash initialization code

- components/bootloader_support/bootloader_flash/include/bootloader_flash_priv.h
- zephyr/common/soc_init.c
- zephyr/port/boot/esp_image_loader.c
- zephyr/port/bootloader/bootloader_flash.c
Changes bootloader calls related to flash access
to reflect its real usage.
> flash: use esp_rom_flash prefix instead bootloader

- zephyr/port/include/boot/mcuboot_config/mcuboot_logging.h
By using the ESP_EARLY_LOG macros we are adding 2nd newline that breaks the console visual at the MCUboot part. This PR fixes it.
> zephyr: port: mcuboot_logging newline

- zephyr/port/host_flash/cache_utils.c
Make sure to use ESP32 low level CPU reading
when cache is disabled. This fixes the scenario
when Optimization is off.
> cache: get cpu id from register

- components/esp_hw_support/include/esp_private/esp_riscv_intr.h
- components/esp_hw_support/port/esp32c2/esp_cpu_intr.c
- components/esp_hw_support/port/esp32c3/esp_cpu_intr.c
- components/esp_hw_support/port/esp32c6/esp_cpu_intr.c
- components/esp_timer/private_include/esp_timer_impl.h
- components/esp_timer/src/esp_timer.c
- components/esp_timer/src/esp_timer_impl_lac.c
- components/esp_timer/src/esp_timer_impl_systimer.c
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c3/src/bt/esp_bt_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32c6/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
Shared allocator for Xtensa and RISCV
> intc: Shared allocator for Xtensa and RISCV

- zephyr/common/esp_restart.c
- zephyr/esp32/CMakeLists.txt
- zephyr/esp32/src/bt/esp_bt_adapter.c
- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32s2/CMakeLists.txt
- zephyr/esp32s3/CMakeLists.txt
- zephyr/port/wifi/wifi_init.c
This creates a common esp_restart call to be used across the system and also implements the shutdown handler, needed for Wi-Fi, BLE and esp_timer(TBD).
> esp_restart: add proper shutdown handlers

- components/esp_psram/mmu_psram_flash.c
- components/spi_flash/spi_flash_os_func_app.c
- zephyr/esp32s3/CMakeLists.txt
- zephyr/port/include/esp_heap_adapter.h
Allow to use PSRAM code relocation on ESP32-S3.
> esp32s3: psram:  add sources to suport code relocation

- zephyr/port/pincfgs/esp32c6.yml
> pinctrl: esp32c6: Add TWAI support

- components/bootloader_support/include/esp_flash_partitions.h
- components/bootloader_support/src/bootloader_console_loader.c
- components/bootloader_support/src/esp32/bootloader_esp32.c
- components/bootloader_support/src/esp32c2/bootloader_esp32c2.c
- components/bootloader_support/src/esp32c3/bootloader_esp32c3.c
- components/bootloader_support/src/esp32c6/bootloader_esp32c6.c
- components/bootloader_support/src/esp32s2/bootloader_esp32s2.c
- components/bootloader_support/src/esp32s3/bootloader_esp32s3.c
- components/esp_common/include/esp_compiler.h
- components/esp_hw_support/include/esp_cpu.h
- zephyr/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
These changes were made to skip building the hal sources from zephyr/<SOC>/CMakeLists.txt when building MCUboot Espressif port from Zephyr's sysbuild as it already have it's own way for integrating the Espressif hal. 
This PR is needed for the MCUboot Espressif Port integration with Zephyr's sysbuild (PRs to be opened in both MCUboot and Zephyr repositories).
> mcuboot: build MCUboot Espressif Port with Zephyr sysbuild

- zephyr/scripts/partitions/esp_genpartition.py
Added "sys" partition for the virtual efuse usage.
> zephyr: scripts: partition generator

- zephyr/esp32c6/CMakeLists.txt
- zephyr/port/pincfgs/esp32c6.yml
Add pinctrl config for ESP32-C6.
> pinctrl: esp32c6: Add i2s pins config

- tools/idf_monitor/idf_monitor_base/console_reader.py
When CTRL+C is pressed, terminal should be closed without spilling out any error. This fixes it.
> monitor: fix output error when exiting

- components/esp_rom/esp32c2/ld/esp32c2.rom.newlib.ld
ROM call is causing reentrant null pointer.
As a workaround, use provided libc version.
> esp32c2: rom: use puts from system libc

- components/esp_hw_support/esp_clk.c
> esp_clk: remove sys/lock.h leftover

- zephyr/esp32s3/src/coex/esp_coex_adapter.c
- zephyr/esp32s3/src/wifi/esp_wifi_adapter.c
- zephyr/port/include/esp_heap_adapter.h
Use SPIRAM option when allocating Wi-Fi buffers.
> SPIRAM option for Wi-Fi adapter

- zephyr/port/include/esp_heap_adapter.h
Fix build issues on ESP32-S2,C6 platforms introduced by included file.
> zephyr: port: esp_heap_adapter fix

- components/esp_hw_support/sleep_modes.c
Fix sleep routine for ESP32-C6 after regression when updating HAL to v.5.1.c (PR #335).
> hal: esp32c6: Fix sleep routine

- components/esp_hw_support/port/esp32/esp_cpu_intr.c
- zephyr/esp32/CMakeLists.txt
Make sure to use proper BLE core kconfig entry to update ESP32 interrupt table descriptor.
> esp32: fix interrupt allocator descriptor checks

- zephyr/esp32/src/coex/esp_coex_adapter.c
- zephyr/esp32/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c2/src/coex/esp_coex_adapter.c
- zephyr/esp32c2/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c3/src/coex/esp_coex_adapter.c
- zephyr/esp32c3/src/wifi/esp_wifi_adapter.c
- zephyr/esp32c6/src/coex/esp_coex_adapter.c
- zephyr/esp32c6/src/wifi/esp_wifi_adapter.c
- zephyr/esp32s2/src/coex/esp_coex_adapter.c
- zephyr/esp32s2/src/wifi/esp_wifi_adapter.c
Wi-Fi adapter internal wrappers must allocate buffers from the main heap (internal RAM) and never from SPIRAM.
This change updates all adapter files to make consistent approach.
Fix https://github.com/zephyrproject-rtos/zephyr/issues/92823
> wifi: fix internal malloc wrappers reference

- components/ulp/lp_core/lp_core.c
- components/ulp/lp_core/lp_core/include/ulp_lp_core_interrupts.h
- components/ulp/lp_core/lp_core/lp_core_interrupt.c
Add support for arguments in ULP interrupt handler.
Do not clear shared memory in initialization.
> ulp: improve interrupt handler for ULP

- zephyr/requirements.txt
Move the esptool requirements to use esptool 5.0.2, which comes with an importand bugfixes that affect the image loading.
> zephyr: esptool requirements

- zephyr/esp32c2/CMakeLists.txt
This file is needed globally to support deep-sleep call.
> esp32c2: move sleep source to common area

- components/soc/esp32s3/include/soc/system_reg.h
- zephyr/port/include/boot/mcuboot_config/mcuboot_config.h
- Get MCUBOOT_BOOT_MAX_ALIGN value from DT - This change affects only MCUboot Zephyr Port for ESP chips or Zephyr application with MCUboot compatibilty (which builds the bootutil lib).
- Wrap typo fix with ifdef for MCUboot Espressif Port compatibility - The typo fix is not present on the original version of ESP-IDF used by MCUboot, thus the partial reverting of the fix.
> espressif: mcuboot: get MCUBOOT_BOOT_MAX_ALIGN value from DT

- components/driver/gpio/rtc_io.c
- components/hal/esp32h2/include/hal/clk_gate_ll.h
- zephyr/esp32h2/CMakeLists.txt
- zephyr/port/pincfgs/esp32h2.yml
Add HAL files and pinctrl for the following peripherals:
- ADC
- I2C
- I2S
- LEDC PWM
- MCPWM
- PCNT
- SPI
- GDMA
- TWAI
- USB serial
> hal: esp32h2: Add peripherals support

- components/soc/esp32c6/include/soc/clk_tree_defs.h
Remove extra `F` from clock value.
> ll: i2s: esp32c6: fix frequency value typo

- zephyr/esp32c2/CMakeLists.txt
- zephyr/esp32c3/CMakeLists.txt
- zephyr/esp32c6/CMakeLists.txt
- zephyr/esp32h2/CMakeLists.txt
- zephyr/port/host_flash/cache_utils.c
Until recently, RISC-V SoCs were using a custom interrupt controller driver on Zephyr, which didn't implement esp_intr_noniram_enable() and esp_intr_noniram_disable() functions. Now that all SoCs share the same interrupt controller driver, these functions can be called for RISC-V chips.
> hal: riscv: Fix noniram enable/disable

- zephyr/port/bluetooth/bt_stubs.c
Compile with no blobs for CI testing.
> ble: esp32h2: Compile with no blobs
