zephyrproject-rtos/hal_espressif

requirements.txt, west/update.py
Fixed python lint issues
Fixed requirements.txt due to build error
=> west: fix remote origin

.gitmodules
remove esp-idf dependent components
=> submodules: remove unused components

west/update.py
Added tools download call
Fix remote path URL
=> west: update installing process

tools/zephyr_tools.json, west/update.py, west/west-commands.yml
Let update command only for submodules update
Added install command for toolchain download
=> west: split west commands

zephyr/CMakeLists.txt, zephyr/adapter/include/wifi/esp_event.h, zephyr/adapter/include/wifi/esp_networking_priv.h, zephyr/adapter/include/wifi/esp_wifi_system.h, zephyr/adapter/src/wifi/esp_event.c, zephyr/adapter/src/wifi/esp_system_api.c, zephyr/adapter/src/wifi/esp_wifi_adapter.c
all porting related sources moved to hal repository
=> wifi: move wifi porting to hal

zephyr/adapter/src/wifi/esp_event.c
Signed-off-by: Mahavir Jain <mahavir@espressif.com>
=> esp_event: update config option names per upstream Zephyr WiFi PR

zephyr/esp32/src/common/esp_system_api.c
Clean up to remove unused common api
=> hal: reboot: remove unused api

components/xtensa/include/xtensa/xtensa_api.h, zephyr/esp32/CMakeLists.txt
Add interrupt allocator hal support.
Signed-off-by: Glauber Maroto Ferreira <glauber.ferreira@espressif.com>
=> hal: intc: add interrupt allocator hal support

components/esp_timer/src/esp_timer.c, zephyr/esp32/src/wifi/esp_wifi_adapter.c
Add thread naming and fix esp timer stack size
=> threads: fix esp timer thread stack usage

components/hal/esp32s2/include/hal/cpu_ll.h, tools/zephyr_tools.json, zephyr/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp32s2/src/linker/esp32s2.rom.alias.ld
=> hal: esp32s2 bringup support

components/esp_wifi/src/phy_init.c
This PR replaces the locking mechanism of esp_phy by an nestable critical section that fixes potential assertion in task switching. 
=> esp_wifi: fix phy locking mechanism

tools/kconfig_new/confgen.py
=> pylint: fix import local error

tools/kconfig_new/confgen.py
=> pylint: fix module import ordering

west/tools.py
=> toolchain: allow selecting installation path

zephyr/esp32/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp_shared/components/driver/dac_common.c, zephyr/esp_shared/components/driver/rtc_io.c, zephyr/esp_shared/components/driver/rtc_io_hal.c, zephyr/esp_shared/pincfgs/esp32.yml
Initial support of DAC on ESP32
=> hal: esp32: dac: Add support for DAC controller node

zephyr/esp_shared/include/stubs.h
Signed-off-by: Marek Matej <marek.matej@espressif.com>
=> system: soc: Remove error check when console not used

components/hal/esp32/include/hal/i2c_ll.h, components/hal/esp32c3/include/hal/i2c_ll.h, components/hal/esp32s2/include/hal/i2c_ll.h, components/hal/esp32s3/include/hal/i2c_ll.h, components/hal/i2c_hal.c, components/hal/include/hal/i2c_hal.h
Signed-off-by: Lucas Tamborrino <lucas.tamborrino@espressif.com>
=> hal: i2c: add timeout enable api

zephyr/esp32/CMakeLists.txt, zephyr/esp32c3/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt
Add required files to read reset reason on hwinfo driver
=> driver: hwinfo: esp32xx: add files to enable reading reset reason

components/driver/esp32c3/rtc_tempsensor.c, components/driver/esp32s2/rtc_tempsensor.c
This removes FreeRTOS entries that are not used.
=> sensor: remove unused includes im temperature sensor

components/hal/esp32s3/include/hal/interrupt_controller_ll.h, components/spi_flash/esp32s3/flash_ops_esp32s3.c, zephyr/esp32s3/CMakeLists.txt, zephyr/esp_shared/include/host_flash/cache_utils.h, zephyr/esp_shared/src/host_flash/cache_utils.c
Add support for spiflash to esp32s3.
=> drivers: flash: esp32s3: Add spiflash support

zephyr/esp_shared/include/boot/bootloader_init_common.h
=> Add missing header

components/esp_hw_support/port/esp32s3/spiram.c, components/esp_hw_support/port/esp32s3/spiram_psram.c, zephyr/esp32s3/CMakeLists.txt
=> hal: esp32s3: add support for SPIRAM

components/esp_timer/src/esp_timer_impl_lac.c, zephyr/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt, zephyr/esp_shared/include/stubs.h
Allows appcpu to me merged into esp32s3 SoC.
=> soc: esp32s3: update hal to allow appcpu usage

zephyr/esp32/src/bt/esp_bt_adapter.c, zephyr/esp32/src/wifi/esp_wifi_adapter.c, zephyr/esp32/src/wpa_supplicant/port/os_xtensa.c, zephyr/esp32c3/src/bt/esp_bt_adapter.c, zephyr/esp32c3/src/wifi/esp_wifi_adapter.c, zephyr/esp32c3/src/wpa_supplicant/port/os_riscv.c, zephyr/esp32s2/src/wifi/esp_wifi_adapter.c, zephyr/esp32s2/src/wpa_supplicant/port/os_xtensa.c, zephyr/esp32s3/src/bt/esp_bt_adapter.c, zephyr/esp32s3/src/wifi/esp_wifi_adapter.c, zephyr/esp32s3/src/wpa_supplicant/port/os_xtensa.c
Follows Zephyr updates regarding random include header.
=> random: rename header file as in Zephyr.

components/esp_phy/include/phy.h
Compiler complained about implicit fn after commit ddfe5f8
=> phy: Squash compiler warning

components/hal/esp32/include/hal/sdmmc_ll.h, components/soc/esp32/include/soc/clk_tree_defs.h, components/soc/esp32/include/soc/sdmmc_struct.h, zephyr/port/pincfgs/esp32.yml
Additional LL files for SDHC driver, as well as pinctrl configuration
=> driver: sdhc: ESP32 pinctrl config for SDHC

zephyr/port/include/stubs.h
Files adjustments to comply with new rtc driver implementation
=> zephyr: Comply with rtc driver refactor

zephyr/esp32c3/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt
=> zephyr: add support for xt wdt

components/esp_timer/src/esp_timer.c
A recursive lock was using the same key storage resulting the initial interrupt and system state being overwritten.
Removed the recursive lock and added an assert() to catch this in the future.
Fixes #74277
=> esp-hal-components: esp_timer: fix recursive lock overwriting key

components/driver/deprecated/adc_legacy.c
Remove unused function build warning
=> hal: remove additional unused functions

components/driver/deprecated/adc_legacy.c
Remove unused function build warning
=> hal: remove extra unused functions

components/driver/deprecated/rtc_temperature_legacy.c
Removes temperature source file constructor.
=> hal: temperature: remove constructor attribute

components/esp_hw_support/port/esp32c6/sar_periph_ctrl.c, components/esp_hw_support/sleep_clock.c, components/esp_hw_support/sleep_cpu.c, components/esp_hw_support/sleep_modes.c, components/esp_hw_support/sleep_retention.c, components/esp_pm/pm_impl.c, components/hal/esp32c3/include/hal/uart_ll.h, components/hal/esp32h2/include/hal/uart_ll.h, components/hal/esp32s2/include/hal/uart_ll.h, components/hal/esp32s3/include/hal/uart_ll.h, components/soc/esp32/include/soc/soc_caps.h, components/soc/esp32c3/include/soc/soc_caps.h, components/soc/esp32c6/include/soc/lp_uart_struct.h, components/soc/esp32h2/include/soc/soc_caps.h, components/soc/esp32s2/include/soc/soc_caps.h, components/soc/esp32s3/include/soc/soc_caps.h, zephyr/esp32c6/CMakeLists.txt
Add LL files for power management for C6
=> hal: esp32c6: Power management support

zephyr/Kconfig
Add config related to sleep modes.
=> zephyr: Add sleep related config

components/driver/deprecated/i2s_legacy.c, components/hal/i2s_hal.c, components/hal/include/hal/i2s_types.h, zephyr/esp32c3/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt, zephyr/port/pincfgs/esp32c3.yml, zephyr/port/pincfgs/esp32s3.yml
added i2s support for esp32-s3 and esp32-c3
=> hal: esp32s3/esp32c3: add I2S support

west/tools.py
Allows using runners.yaml argument to set a specific default baudrate for ESP monitor.
Required for C2 support.
=> tools: monitor: Get baud rate from runners.yaml

zephyr/CMakeLists.txt, zephyr/esp32c2/CMakeLists.txt, zephyr/esp32c2/src/wifi/esp_wifi_adapter.c
LL files for wifi support on ESP32C2 and ESP8684
=> hal: esp32c2: Add wifi support to ESP32C2

components/hal/cam_hal.c, components/hal/esp32s3/include/hal/cam_ll.h, components/hal/include/hal/cam_ctlr_types.h, components/hal/include/hal/cam_hal.h, components/hal/include/hal/cam_types.h, components/hal/include/hal/color_types.h, zephyr/esp32s3/CMakeLists.txt, zephyr/port/pincfgs/esp32s3.yml
Add CAM files to provide a proper HAL API
for Zephyr's camera driver.
=> hal: add CAM HAL files

components/esp_adc/deprecated/esp_adc_cal_common_legacy.c, components/hal/adc_hal_common.c
Fix build warning for adc source files.
=> components: adc: fix build warnings

zephyr/esp32c2/CMakeLists.txt
Adds HAL files for embedded temperature sensor
=> hal: esp32c2: Temperature sensor

zephyr/Kconfig, zephyr/esp32s2/CMakeLists.txt, zephyr/port/boot/esp_image_loader.c
Enable RTC segment loading as needed.
=> mcuboot: loader: enable RTC segment loading

zephyr/scripts/partitions/esp_genpartition.py
Adding the partition generator script which simplified the creation and updates of the partition tables for various of flash sizes and schemes.
=> zephyr: scripts: partitions generator

components/hal/adc_hal_common.c, zephyr/esp32/CMakeLists.txt, zephyr/esp32c2/CMakeLists.txt, zephyr/esp32c3/CMakeLists.txt, zephyr/esp32c6/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt
Driver update to support newer HAL versions.
=> adc: esp32: Driver update

components/bootloader_support/bootloader_flash/include/bootloader_flash_priv.h, zephyr/port/boot/esp_image_loader.c, zephyr/port/bootloader/bootloader_flash.c
=> flash: fix unmap function name

zephyr/esp32/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/port/pincfgs/esp32.yml, zephyr/port/pincfgs/esp32s2.yml
Add i2s support for esp32 and esp32s2
=> esp32 & esp32s2: i2s support

zephyr/esp32c2/CMakeLists.txt, zephyr/esp32c3/CMakeLists.txt, zephyr/esp32c6/CMakeLists.txt, zephyr/esp32s2/CMakeLists.txt, zephyr/esp32s3/CMakeLists.txt
Adds HAL files for embedded temperature sensor.
=> zephyr: esp32c6: Temperature sensor

components/esp_hw_support/port/esp32c6/rtc_clk.c, components/hal/esp32c6/clk_tree_hal.c, components/hal/esp32c6/include/hal/uart_ll.h, zephyr/esp32c6/CMakeLists.txt
Add LP UART support for LP Core on C6
=> zephyr: Add LP UART support for C6

components/hal/esp32c6/include/hal/rtc_io_ll.h, zephyr/esp32c6/CMakeLists.txt
* Add LP GPIO sources to LP Core build
* update RTC IO LL
=> zephyr: esp32c6: add LP GPIO

zephyr/esp32s3/src/bt/esp_bt_adapter.c
Set BLE priority equal to WiFi.
=> Unify WiFi and BLE priority

zephyr/esp32c6/CMakeLists.txt, zephyr/port/pincfgs/esp32c6.yml
Add pinctrl and HAL file for PCNT support.
=> soc: esp32c6: Add PCNT support

zephyr/port/include/esp_heap_adapter.h
* fix typo in SPIRAM config
* make SMH allocators inline
=> zephyr: port: Heap adapter

components/esp_phy/src/btbb_init.c, components/esp_timer/src/esp_timer.c, components/ieee802154/CMakeLists.txt, components/ieee802154/Kconfig, components/ieee802154/driver/esp_ieee802154_ack.c, components/ieee802154/driver/esp_ieee802154_debug.c, components/ieee802154/driver/esp_ieee802154_dev.c, components/ieee802154/driver/esp_ieee802154_frame.c, components/ieee802154/driver/esp_ieee802154_pib.c, components/ieee802154/driver/esp_ieee802154_sec.c, components/ieee802154/driver/esp_ieee802154_timer.c, components/ieee802154/driver/esp_ieee802154_util.c, components/ieee802154/esp_ieee802154.c, components/ieee802154/include/esp_ieee802154.h, components/ieee802154/include/esp_ieee802154_types.h, components/ieee802154/linker.lf, components/ieee802154/private_include/esp_ieee802154_ack.h, components/ieee802154/private_include/esp_ieee802154_dev.h, components/ieee802154/private_include/esp_ieee802154_frame.h, components/ieee802154/private_include/esp_ieee802154_pib.h, components/ieee802154/private_include/esp_ieee802154_sec.h, components/ieee802154/private_include/esp_ieee802154_timer.h, components/ieee802154/private_include/esp_ieee802154_util.h, zephyr/esp32c6/CMakeLists.txt, zephyr/module.yml, zephyr/scripts/submodules.txt
Updated initial hal support for the IEEE802154 for the ESP32-C6.
=> Updated IEEE802154 support on  ESP32-C6

components/esp_hw_support/port/esp32c6/rtc_time.c
ECO1 version requires a different calibration than previous version.
=> esp32c6: fix RTC calibration for ECO1 rev

zephyr/module.yml, zephyr/scripts/blobs/esp_genblobs.py, zephyr/scripts/filters.yml
Add yaml filter file to allow fetching only the actually used libraries from the repositories for each SoC.
=> scripts: blobs: Add filter to fetch only used libs
